[package]
name = "sensitive-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.sensitive-core]
path = "../crates/sensitive-core"

[dependencies.sensitive-extract]
path = "../crates/sensitive-extract"

[[bin]]
name = "scan_engine"
path = "fuzz_targets/scan_engine.rs"
test = false
doc = false
bench = false

[[bin]]
name = "archive_zip"
path = "fuzz_targets/archive_zip.rs"
test = false
doc = false
bench = false