[package]
name = "sensitive-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI de scan — le premier livrable de ProjectSecurityScanner."

[[bin]]
name = "scanner"
path = "src/main.rs"

[dependencies]
sensitive-core = { path = "../sensitive-core" }
sensitive-extract = { path = "../sensitive-extract" }
serde_json.workspace = true
serde_yaml.workspace = true
clap = { version = "4", features = ["derive"] }
chardetng = "0.1"
encoding_rs = "0.8"
zeroize.workspace = true

[dev-dependencies]
zip = { version = "2", default-features = false, features = ["deflate"] }
